name = "SeisBeamforming"
uuid = "c872090a-913f-11e9-2a50-4b83414f27c6"
authors = ["kurama"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
